service: urlshortener

frameworkVersion: '2'

custom:
  stage: ${opt:stage, self:provider.stage}
  devDynamoCapacity:
    ReadCapacityUnits: 1
    WriteCapacityUnits: 1
  prodDynamoCapacity:
    ReadCapacityUnits: 5
    WriteCapacityUnits: 5
provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLS_STAGE: ${self:custom.stage}
    DDB_TABLE: {Ref: LinkDB}
  iamRoleStatements:
    - Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        "Fn::Join":
          - ""
          -
            - "arn:aws:dynamodb:"
            - Ref: "AWS::Region"
            - ":"
            - Ref: "AWS::AccountId"
            - ":table/"
            - Ref: LinkDB
      Effect: Allow

functions:
  main:
    handler: main/index.handler
    events:
      - http:
          path: /
          method: get
  create:
    handler: create/index.handler
    events:
      - http:
          path: /
          method: post
  redirect:
    handler: redirect/index.handler
    events:
      - http:
          path: /{slug}
          method: get

resources:
  Resources:
    LinkDB:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: slug
            AttributeType: S
        KeySchema:
          - AttributeName: slug
            KeyType: HASH
        ProvisionedThroughput: ${self:custom.${self:custom.stage}DynamoCapacity}
    CustomDomainMap: 
      Type: "AWS::ApiGateway::BasePathMapping"
      Properties:
        DomainName: urlshortener.cosimplify.com
        Stage: ${self:custom.stage}
        RestApiId: {Ref: ApiGatewayRestApi}
