service: urlshortener

frameworkVersion: '2'

custom: 
  stage: ${opt:stage, self:provider.stage}
  devDynamoCapacity: 
    ReadCapacityUnits: 1
    WriteCapacityUnits: 1
  prodDynamoCapacity: 
    ReadCapacityUnits: 5
    WriteCapacityUnits: 5 
 
provider: 
  name: aws
  runtime: nodejs12.x
  environment: 
    SLS_STAGE: ${self:custom.stage}
  iamRoleStatements:
    - Action: 
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:us-east-1:414416947237:table/${self:custom.stage}-shortened-urls"
      Effect: Allow

functions: 
  main:
    handler: main/index.handler
    events:
      - http:
          path: /
          method: get

  create:
    handler: create/index.handler
    events:
      - http:
          path: /
          method: post

  redirect:
    handler: redirect/index.handler
    events: 
      - http:
         path: /{slug}
         method: get
    
resources:
  Resources:
    LinkDB:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: slug
            AttributeType: S
        KeySchema:
          - AttributeName: slug
            KeyType: HASH
        ProvisionedThroughput: ${self:custom.${self:custom.stage}DynamoCapacity}
        TableName: "${self:custom.stage}-shortened-urls"
